//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kahveDiyarı.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using System.Web.Mvc;
    
    public partial class hakkimizda
    {
        public int id { get; set; }
        public string foto { get; set; }

        public virtual HttpPostedFileBase fotoFile { get; set; }

        [Required]
        [Display(Name="Başlık")]
        public string baslik { get; set; }

        [Required]
        [Display(Name = "Üst Başlık")]
        public string ustbaslik { get; set; }

        [AllowHtml]
        [Required]
        [Display(Name = "İçerik")]
        public string icerik { get; set; }
    }
}
