//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kahveDiyarı.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class urunler
    {
        public int id { get; set; }
        public string foto { get; set; }
        public string baslik { get; set; }
        public string ustbaslik { get; set; }
        public string icerik { get; set; }
        public Nullable<bool> aktif { get; set; }
        public Nullable<int> sira { get; set; }
    }
}
